### ISSUE TITLE
--p-n-jobs should be renamed for qiime2-2021.8

### ISSUE THREAD

**Issue by lina-kim** [qiime2/paper2#14]
**Bug Description**
The given command for computing diversity uses an outdated flag `--p-n-jobs`. The latest release of QIIME 2 (core 2021.8 distribution) renamed this to `--p-n-jobs-or-threads`.

**Steps to reproduce this behavior**
1. Follow the tutorial
2. Error out running `qiime diversity core-metrics-phylogenetic`, found twice in the alpha diversity section

**Comment by thermokarst** [comment]
Hi @lina-kim - this tutorial is written specifically for QIIME 2 2019.10. We can keep this issue around in case we update the tutorial to a more recent version, but for now you'll need to stick to 2019.10. Thanks!
