### ISSUE TITLE
Songbird installation in conflict with QIIME 2 release 2021.8

### ISSUE THREAD

**Issue by lina-kim** [qiime2/paper2#15]
**Bug Description**
Instructions for `songbird` installation on top of the latest QIIME 2 distribution cause errors. It appears the latest version of `songbird` is at odds with the QIIME 2 environment's Python version.

**Steps to reproduce the behavior**
1. Install QIIME 2 core distribution (release 2021.8) in conda virtual environment
2. Follow [tutorial instructions](https://curr-protoc-bioinformatics.qiime2.org/#songbird) to install `songbird` in the environment: `conda install songbird -c conda-forge`
3. See error screenshot below

**Screenshots**
![Screenshot 2021-11-09 at 14 57 26](https://user-images.githubusercontent.com/25010133/141287405-9a97dead-1cc6-4ffe-b8c9-79534f35bda3.png)

**Computation Environment**
- OS: macOS Big Sur
- QIIME 2 Release 2021.8, in conda environment

**Comment by thermokarst** [comment]
Hi @lina-kim - this tutorial is written specifically for QIIME 2 2019.10. We can keep this issue around in case we update the tutorial to a more recent version, but for now you'll need to stick to 2019.10. Thanks!
